# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: d702e2ff3cc7a5e16a2dacb01c0afca2f842dd833026ff6ee2f71ecfac87b937d760665fbbbd003ca779b6b73e9aea4c454b416fc1d6b3e0554c700e96ccc676

test:
  domain_name: example.com 
  secret_key_base: 72fdfe9a87dac9449cfc9086c57e71e3bdcac2f84b89bef718481ae574fde205f287135083b0f5fcb40275f4b5e3819b3751e881f56926dd05390e2e88b4f5ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
